# Generated by Django 4.1.13 on 2025-12-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['prazo', '-data_criacao'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank='True', null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
    ]
